# Generated by Django 5.1.5 on 2025-02-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_feed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='feed_image',
            new_name='header_image',
        ),
    ]
